### ISSUE TITLE
Wiki Feedback

### ISSUE THREAD

**Issue by GordonRBurgess** [Nickoliz/game-share#1]
# Wiki Feedback

After you have reviewed and addressed these changes, please respond to this issue and send Gordon and Ed a link. We will provide followup after reviewing your changes before closing this issue.

## MVP List
- [x] This list looks generally solid.
- [ ] There is no provision to loan or sell a game.  This might be difficult to fully implement this week, but it should probably be a target for full development of this concept. 

## Schema
- Do not feel you have to use my nomenclature for your classes/tables - the point made below has to do with different levels of 'kinds of things' as opposed to 'instances of things' - the coolest systems I have worked on have these kinds of levels to them - as do all databases, which themselves store data describing the data that they hold (metadata).
- [x] You need to separate the type class `BoardGame` - like `Monopoly (classic edition)` (this is metadata, about a kind of thing) -  from the instance class `BoardGame` - like - "I have an old `Monopoly (classic edition)` that I bought in 1998 that is in fair condition, and that I'd be willing to loan or trade for a good chess set"   (and yes, you might even have "Monopoly" as a `Game` and "Monopoly Classic Edition" as a `GameVersion` and "my third copy of Monopoly Classic, in Mint condition, which I will sell for $50" as a `GameInstance`) 
- [x] Once you separate `GameVersion` data from `GameInstance` data, it will be obvious where the instance data goes.  You may not even need the `UserCollection` table, since every `GameInstance` will have an owner.  (You might need another table if you want the users to be able to create "bundles" for sale or borrowing - but that's a stretch goal)

## Back End Routes
- [x] Your routes look solid in general.  This list should probably be expanded to distinguish routes between `GameVersion` (or even `Game`) objects and `GameInstance` objects.

## Front End Routes
- [x] there do not appear to be any routes to support defining `Game`s or `GameVersion`s or `GameInstance`s (aka 'my collection`)  I know you are planning to pull games (and perhaps versions?) from an API which is all good - but  I think you're still going to need to support editing the user's collection.

## Wireframes
- The home page looks nice.
- [x] More pages are needed.

**Comment by Nickoliz** [comment]
Great feedback, Gordon - thank you.

I provided more front end routes for things like users collections (by type - trade, borrow, sale, buy, the main profile will be ALL in collection).

I'll get to the wireframes shortly. I do want to do them for layout but I'd like to get functional things done this week while I have you and Ed to call for help. This weekend I'll tackle wire frames.

I honestly like the feedback for the db with GameVersion and GameInstance. I think I already have it. I'm going to use the API to be the "instance" of the game since I have access to all games known to man. Then the BoardGame class is going to be the individual instances for each user that owns the game. Within that I will make it so they are required to provide the condition of the game with details of the condition if they are listing it for sell/trade/borrow (there will be validators for this if they choose sell/trade/borrow - if they're just listing the game in their collection and don't plan to sell/trade/borrow then they don't need to provide condition details - that's going to be a lot of work. haha)

My reasoning for the above is because within the board gaming hobby there is a divide between collectors and playing enthusiast. Those playing don't necessarily care about the versioning unless it's 2nd print with extra chits, expansions, etc. If that's the case it is usually listed in as a memo. Why? Because no site tracks the printing version of the game but all sites track the version of the game (Viticulture vs. Viticulture: Essentials Edition) but two separate instances.

Does this make sense? Am I okay to leave as is and update the schema to include more information about the user collection instance?
